force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>purpose</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TransactionController.cls
public class TransactionController {
    
    public List<Transaction__c> getTransactions() {
        return [select id, name, amount__c, createdDate, ownerId from Transaction__c
                where ownerId = :userInfo.getUserId() order by createdDate desc];
    }
    
    public void removeTransaction()
    {
        Id cId = ApexPages.currentPage().getParameters().get('delTransaction');
        Transaction__c tr = [select Id, name from Transaction__c where id = :cId];
        delete tr;
        
    }
    
    public PageReference editTransaction()
    {
        PageReference pageRef= new PageReference('/'+ApexPages.currentPage().getParameters().get('editTransaction'));
        pageRef.setredirect(true);
        return pageRef;
                
    }
    
}